# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generatorView_v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Generator(object):
    def setupUi(self, Generator):
        Generator.setObjectName("Generator")
        Generator.resize(633, 358)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.barcodeTitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.barcodeTitle.setObjectName("barcodeTitle")
        self.horizontalLayout.addWidget(self.barcodeTitle)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.barcodeHead = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.barcodeHead.setMaxLength(3)
        self.barcodeHead.setObjectName("barcodeHead")
        self.horizontalLayout.addWidget(self.barcodeHead)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.barcodeBody = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.barcodeBody.setMaxLength(3)
        self.barcodeBody.setObjectName("barcodeBody")
        self.horizontalLayout.addWidget(self.barcodeBody)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.barcodeTail = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.barcodeTail.setMaxLength(6)
        self.barcodeTail.setObjectName("barcodeTail")
        self.horizontalLayout.addWidget(self.barcodeTail)
        spacerItem2 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 611, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.csvTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.csvTitle.setObjectName("csvTitle")
        self.horizontalLayout_2.addWidget(self.csvTitle)
        spacerItem4 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.csvPathDisplay = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.csvPathDisplay.setReadOnly(True)
        self.csvPathDisplay.setObjectName("csvPathDisplay")
        self.horizontalLayout_2.addWidget(self.csvPathDisplay)
        self.csvUploadButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.csvUploadButton.setObjectName("csvUploadButton")
        self.horizontalLayout_2.addWidget(self.csvUploadButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 611, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.savePathTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.savePathTitle.setObjectName("savePathTitle")
        self.horizontalLayout_5.addWidget(self.savePathTitle)
        spacerItem6 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.savePathDisplay = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.savePathDisplay.setReadOnly(True)
        self.savePathDisplay.setObjectName("savePathDisplay")
        self.horizontalLayout_5.addWidget(self.savePathDisplay)
        self.savePathButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.savePathButton.setObjectName("savePathButton")
        self.horizontalLayout_5.addWidget(self.savePathButton)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 100, 611, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.extenstionTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.extenstionTitle.setObjectName("extenstionTitle")
        self.horizontalLayout_6.addWidget(self.extenstionTitle)
        spacerItem8 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.extensionComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.extensionComboBox.setObjectName("extensionComboBox")
        self.extensionComboBox.addItem("")
        self.extensionComboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.extensionComboBox)
        spacerItem9 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 310, 581, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.genButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.genButton.setObjectName("genButton")
        self.horizontalLayout_7.addWidget(self.genButton)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_7.addWidget(self.clearButton)
        spacerItem12 = QtWidgets.QSpacerItem(18, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 260, 611, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.saveAsTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.saveAsTitle.setObjectName("saveAsTitle")
        self.horizontalLayout_8.addWidget(self.saveAsTitle)
        spacerItem14 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.saveAsCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.saveAsCheckBox.setObjectName("saveAsCheckBox")
        self.horizontalLayout_8.addWidget(self.saveAsCheckBox)
        self.saveAsPdfDisplay = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.saveAsPdfDisplay.setReadOnly(True)
        self.saveAsPdfDisplay.setObjectName("saveAsPdfDisplay")
        self.horizontalLayout_8.addWidget(self.saveAsPdfDisplay)
        self.saveAsPdfButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.saveAsPdfButton.setObjectName("saveAsPdfButton")
        self.horizontalLayout_8.addWidget(self.saveAsPdfButton)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 220, 611, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem15 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.batchSaveTitle = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.batchSaveTitle.setObjectName("batchSaveTitle")
        self.horizontalLayout_10.addWidget(self.batchSaveTitle)
        spacerItem16 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.batchSaveDisplay = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.batchSaveDisplay.setReadOnly(True)
        self.batchSaveDisplay.setObjectName("batchSaveDisplay")
        self.horizontalLayout_10.addWidget(self.batchSaveDisplay)
        self.batchSaveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.batchSaveButton.setObjectName("batchSaveButton")
        self.horizontalLayout_10.addWidget(self.batchSaveButton)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(Generator)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 140, 611, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.isBatchMode = QtWidgets.QCheckBox(self.horizontalLayoutWidget_8)
        self.isBatchMode.setObjectName("isBatchMode")
        self.horizontalLayout_3.addWidget(self.isBatchMode)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)

        self.retranslateUi(Generator)
        QtCore.QMetaObject.connectSlotsByName(Generator)

    def retranslateUi(self, Generator):
        _translate = QtCore.QCoreApplication.translate
        Generator.setWindowTitle(_translate("Generator", "Icons Barcode Generator"))
        self.barcodeTitle.setText(_translate("Generator", "1D Barcode: "))
        self.label_2.setText(_translate("Generator", "-"))
        self.label_4.setText(_translate("Generator", "-"))
        self.csvTitle.setText(_translate("Generator", "1D Barcode file (csv)"))
        self.csvUploadButton.setText(_translate("Generator", "Upload"))
        self.savePathTitle.setText(_translate("Generator", "Barcode Image Path:"))
        self.savePathButton.setText(_translate("Generator", "Save"))
        self.extenstionTitle.setText(_translate("Generator", "Image Extenstion:"))
        self.extensionComboBox.setItemText(0, _translate("Generator", "png"))
        self.extensionComboBox.setItemText(1, _translate("Generator", "gif"))
        self.genButton.setText(_translate("Generator", "Generate Barcode"))
        self.clearButton.setText(_translate("Generator", "Clear All"))
        self.saveAsTitle.setText(_translate("Generator", "Save all image in one PDF:"))
        self.saveAsCheckBox.setText(_translate("Generator", "Yes"))
        self.saveAsPdfButton.setText(_translate("Generator", "Save"))
        self.batchSaveTitle.setText(_translate("Generator", "Barcode Image Path:"))
        self.batchSaveButton.setText(_translate("Generator", "Save"))
        self.isBatchMode.setText(_translate("Generator", "Generate Barcode in Batch Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Generator = QtWidgets.QWidget()
    ui = Ui_Generator()
    ui.setupUi(Generator)
    Generator.show()
    sys.exit(app.exec_())

